package com.github.moonbit.psi

import com.intellij.psi.tree.IElementType

object MoonTypes {
    // Comment tokens
    val COMMENT_LINE: IElementType = MoonTokenType("COMMENT_LINE")
    val COMMENT_DOCUMENT: IElementType = MoonTokenType("COMMENT_DOCUMENT")
    val COMMENT_BLOCK: IElementType = MoonTokenType("COMMENT_BLOCK")

    // Punctuation tokens
    val PARENTHESIS_L: IElementType = MoonTokenType("PARENTHESIS_L")
    val PARENTHESIS_R: IElementType = MoonTokenType("PARENTHESIS_R")
    val BRACKET_L: IElementType = MoonTokenType("BRACKET_L")
    val BRACKET_R: IElementType = MoonTokenType("BRACKET_R")
    val BRACE_L: IElementType = MoonTokenType("BRACE_L")
    val BRACE_R: IElementType = MoonTokenType("BRACE_R")
    val COLON: IElementType = MoonTokenType("COLON")
    val SEMICOLON: IElementType = MoonTokenType("SEMICOLON")
    val COMMA: IElementType = MoonTokenType("COMMA")
    val DOT: IElementType = MoonTokenType("DOT")
    val DOLLAR: IElementType = MoonTokenType("DOLLAR")
    val AT: IElementType = MoonTokenType("AT")

    // Operator tokens
    val OP_XOR: IElementType = MoonTokenType("OP_XOR")
    val OP_ADD: IElementType = MoonTokenType("OP_ADD")
    val OP_ADD_ASSIGN: IElementType = MoonTokenType("OP_ADD_ASSIGN")
    val OP_SUB: IElementType = MoonTokenType("OP_SUB")
    val OP_SUB_ASSIGN: IElementType = MoonTokenType("OP_SUB_ASSIGN")
    val OP_MUL: IElementType = MoonTokenType("OP_MUL")
    val OP_MUL_ASSIGN: IElementType = MoonTokenType("OP_MUL_ASSIGN")
    val OP_DIV: IElementType = MoonTokenType("OP_DIV")
    val OP_DIV_ASSIGN: IElementType = MoonTokenType("OP_DIV_ASSIGN")
    val OP_MOD: IElementType = MoonTokenType("OP_MOD")
    val OP_TO: IElementType = MoonTokenType("OP_TO")
    val OP_LEQ: IElementType = MoonTokenType("OP_LEQ")
    val OP_LL: IElementType = MoonTokenType("OP_LL")
    val OP_LT: IElementType = MoonTokenType("OP_LT")
    val OP_GG: IElementType = MoonTokenType("OP_GG")
    val OP_GT: IElementType = MoonTokenType("OP_GT")
    val OP_GEQ: IElementType = MoonTokenType("OP_GEQ")
    val OP_OR: IElementType = MoonTokenType("OP_OR")
    val OP_BIT_OR: IElementType = MoonTokenType("OP_BIT_OR")
    val OP_THEN: IElementType = MoonTokenType("OP_THEN")
    val OP_AND: IElementType = MoonTokenType("OP_AND")
    val OP_BIT_AND: IElementType = MoonTokenType("OP_BIT_AND")
    val OP_NE: IElementType = MoonTokenType("OP_NE")
    val OP_EQ: IElementType = MoonTokenType("OP_EQ")
    val OP_PATTERN_TO: IElementType = MoonTokenType("OP_PATTERN_TO")
    val OP_ASSIGN: IElementType = MoonTokenType("OP_ASSIGN")
    val OP_ERROR: IElementType = MoonTokenType("OP_ERROR")
    val OP_REF: IElementType = MoonTokenType("OP_REF")
    val OP_THROW: IElementType = MoonTokenType("OP_THROW")
    val OP_RANGE_TO: IElementType = MoonTokenType("OP_RANGE_TO")
    val OP_SPREAD: IElementType = MoonTokenType("OP_SPREAD")
    val NAME_JOIN: IElementType = MoonTokenType("NAME_JOIN")

    // Keyword tokens
    val KW_PACKAGE: IElementType = MoonTokenType("KW_PACKAGE")
    val KW_WORLD: IElementType = MoonTokenType("KW_WORLD")
    val KW_INTERFACE: IElementType = MoonTokenType("KW_INTERFACE")
    val KW_INCLUDE: IElementType = MoonTokenType("KW_INCLUDE")
    val KW_EXPORT: IElementType = MoonTokenType("KW_EXPORT")
    val KW_IMPORT: IElementType = MoonTokenType("KW_IMPORT")
    val KW_USE: IElementType = MoonTokenType("KW_USE")
    val KW_AS: IElementType = MoonTokenType("KW_AS")
    val KW_RESOURCE: IElementType = MoonTokenType("KW_RESOURCE")
    val KW_RECORD: IElementType = MoonTokenType("KW_RECORD")
    val KW_ENUM: IElementType = MoonTokenType("KW_ENUM")
    val KW_FLAGS: IElementType = MoonTokenType("KW_FLAGS")
    val KW_VARIANT: IElementType = MoonTokenType("KW_VARIANT")
    val KW_CONSTRUCTOR: IElementType = MoonTokenType("KW_CONSTRUCTOR")
    val KW_TRAIT: IElementType = MoonTokenType("KW_TRAIT")
    val KW_STRUCT: IElementType = MoonTokenType("KW_STRUCT")
    val KW_PRIVATE: IElementType = MoonTokenType("KW_PRIVATE")
    val KW_MUTABLE: IElementType = MoonTokenType("KW_MUTABLE")
    val KW_LET: IElementType = MoonTokenType("KW_LET")
    val KW_FN: IElementType = MoonTokenType("KW_FN")
    val KW_TEST: IElementType = MoonTokenType("KW_TEST")
    val KW_GUARD: IElementType = MoonTokenType("KW_GUARD")
    val KW_IF: IElementType = MoonTokenType("KW_IF")
    val KW_ELSE: IElementType = MoonTokenType("KW_ELSE")
    val KW_MATCH: IElementType = MoonTokenType("KW_MATCH")
    val KW_WHILE: IElementType = MoonTokenType("KW_WHILE")
    val KW_FOR: IElementType = MoonTokenType("KW_FOR")
    val KW_IN: IElementType = MoonTokenType("KW_IN")
    val KW_RETURN: IElementType = MoonTokenType("KW_RETURN")
    val KW_CONTINUE: IElementType = MoonTokenType("KW_CONTINUE")
    val KW_BREAK: IElementType = MoonTokenType("KW_BREAK")
    val KW_RAISE: IElementType = MoonTokenType("KW_RAISE")
    val KW_TRY: IElementType = MoonTokenType("KW_TRY")
    val KW_CATCH: IElementType = MoonTokenType("KW_CATCH")
    val KW_TYPE: IElementType = MoonTokenType("KW_TYPE")
    val KW_TYPE_ALIAS: IElementType = MoonTokenType("KW_TYPE_ALIAS")
    val KW_DERIVE: IElementType = MoonTokenType("KW_DERIVE")
    val KW_IMPLEMENT: IElementType = MoonTokenType("KW_IMPLEMENT")
    val KW_WITH: IElementType = MoonTokenType("KW_WITH")
    val KW_EXTERN: IElementType = MoonTokenType("KW_EXTERN")
    val KW_PUBLIC: IElementType = MoonTokenType("KW_PUBLIC")
    val KW_ALL: IElementType = MoonTokenType("KW_ALL")
    val KW_OPEN: IElementType = MoonTokenType("KW_OPEN")

    // Literal tokens
    val SYMBOL: IElementType = MoonTokenType("SYMBOL")
    val BYTES_HEX: IElementType = MoonTokenType("BYTES_HEX")
    val BYTES_OCT: IElementType = MoonTokenType("BYTES_OCT")
    val BYTES_BIN: IElementType = MoonTokenType("BYTES_BIN")
    val INTEGER: IElementType = MoonTokenType("INTEGER")
    val STRING_LINE: IElementType = MoonTokenType("STRING_LINE")
    val SINGLE_QUOTE_L: IElementType = MoonTokenType("SINGLE_QUOTE_L")
    val SINGLE_QUOTE_R: IElementType = MoonTokenType("SINGLE_QUOTE_R")
    val DOUBLE_QUOTE_L: IElementType = MoonTokenType("DOUBLE_QUOTE_L")
    val DOUBLE_QUOTE_R: IElementType = MoonTokenType("DOUBLE_QUOTE_R")
    val STRING_TEXT: IElementType = MoonTokenType("STRING_TEXT")

    // Factory for creating elements
    object Factory {
        fun createElement(node: com.intellij.lang.ASTNode): com.intellij.psi.PsiElement {
            return com.github.moonbit.psi.AnyMoonNode(node)
        }
    }
}
